# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: product.proto
# Protobuf Python Version: 5.27.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    3,
    '',
    'product.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rproduct.proto\x12\x07product\"\xa7\x04\n\x07Product\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x14\n\x0c\x64isplay_name\x18\x02 \x01(\t\x12\x11\n\tlst_price\x18\x03 \x01(\x02\x12\x16\n\x0estandard_price\x18\x04 \x01(\x02\x12(\n\x08\x63\x61teg_id\x18\x05 \x01(\x0b\x32\x16.product.Product.Tuple\x12,\n\x0cpos_categ_id\x18\x06 \x01(\x0b\x32\x16.product.Product.Tuple\x12\x10\n\x08taxes_id\x18\x07 \x03(\x05\x12\x0f\n\x07\x62\x61rcode\x18\x08 \x01(\t\x12\x14\n\x0c\x64\x65\x66\x61ult_code\x18\t \x01(\t\x12\x11\n\tto_weight\x18\n \x01(\x08\x12&\n\x06uom_id\x18\x0b \x01(\x0b\x32\x16.product.Product.Tuple\x12\x18\n\x10\x64\x65scription_sale\x18\x0c \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\r \x01(\t\x12/\n\x0fproduct_tmpl_id\x18\x0e \x01(\x0b\x32\x16.product.Product.Tuple\x12\x10\n\x08tracking\x18\x0f \x01(\t\x12\x18\n\x10\x61vailable_in_pos\x18\x10 \x01(\x08\x12\x1a\n\x12\x61ttribute_line_ids\x18\x11 \x03(\x05\x12\x0e\n\x06\x61\x63tive\x18\x12 \x01(\x08\x12\x15\n\r__last_update\x18\x13 \x01(\t\x12\x11\n\timage_128\x18\x14 \x01(\x0c\x1a!\n\x05Tuple\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'product_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PRODUCT']._serialized_start=27
  _globals['_PRODUCT']._serialized_end=578
  _globals['_PRODUCT_TUPLE']._serialized_start=545
  _globals['_PRODUCT_TUPLE']._serialized_end=578
# @@protoc_insertion_point(module_scope)
